CREATE DATABASE vendas;

CREATE TABLE tb_produto(
	ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255),
	PRECO DECIMAL(16,2),
	CODIGO VARCHAR(20),
	DATA_CADASTRO DATE,
	PRIMARY KEY (ID_PRODUTO)
);

ALTER TABLE tb_produto CHANGE preco  PRECO Decimal(16,2)

select * from tb_produto ;
